spring:
  application:
    name: spring-template

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      springframework:
        security: TRACE

jwt:
  issuer: choi-yh-spring-template
  secret_key: ${JWT_SECRET}